Portfolio Setup Mobile first
OrdinaryMack/Portfolio-Setup-Mobile pull request #2
Opened 2023-10-01 02:29 UTC by OrdinaryMack

fixing nav position
fixing media query value

2023-10-04 15:50 UTC, HninSuWai12 commented
Background-image is not appear and should fix for responsive design to be better.

2023-10-05 03:55 UTC, Rhaegar121 requested changes
## STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi @OrdinaryMack 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![close lady](https://user-images.githubusercontent.com/99246359/204822829-8d2e1877-0db5-435f-9e1e-438a33fc65d7.gif)

## Highlights 💯 
- Great design and UI ✔️
- Good commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-10-05 03:58 UTC, Rhaegar121 commented
As I mentioned in the previous project, Please include the description for the Pull Request in your next projects according to the requirements. I have shared an example photo of descriptive pull request in below.

You can see this requirement in this [link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
`Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request.`

![Screenshot (159)](https://github.com/OrdinaryMack/Portfolio-Setup-Mobile/assets/111948881/274b551f-1466-4a07-af0e-4cb8de1964a8)

2023-10-05 04:00 UTC, Rhaegar121 commented on .github/worksflows/linters.yml
I think you misspelled the folder name to `worksflows`, the correct name is **`workflows`**. Please kindly rename the folder so that you can see the linters are running in the pull request.

2023-10-05 04:04 UTC, Rhaegar121 commented on README.md
Please use the readme template provided in the curriculum if possible because you'll see how functional the template is in the later big projects. I think it best to get used to the Microverse readme template from now.

This is the requirement:
`Add descriptive README file to your project - please use this template but remember to customize it to your project.`

You can see the template [here](https://github.com/microverseinc/readme-template).

2023-10-05 04:09 UTC, Rhaegar121 commented
### Optional Suggestion
Please kindly use a descriptive branch name in your next project or next pull request according to this requirement - 
`Branch name should describe a feature or action (e.g. 'created_sidebar' or 'added_comments_section').`

**Note. Although this is an optional suggestion in this pull request, this is mandatory in your later projects. Because you might not know how to rename both the remote branch and the local branch but in your later projects, CR might not approve because of this requirement.**

2023-10-05 09:51 UTC, Rhaegar121 approved these changes
## STATUS: APPROVED 🟢

## Hi @OrdinaryMack 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-10-06 16:47 UTC, closed without merging